-------------------------------------------------------------------------------
-- 4.a PROVIDERS - Optimized with speacialty constraints
CREATE TABLE IF NOT EXISTS core.providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Ensure we don't duplicate the same provider/specialty combo
    CONSTRAINT uniq_provider_spec UNIQUE (provider_name, specialty)
);

-- Add Index for searching by specialty
CREATE INDEX IF NOT EXISTS idx_providers_specialty ON core.providers (specialty);

-------------------------------------------------------------------------------
-- 1. PATIENTS - The anchor for all clinical data
CREATE TABLE IF NOT EXISTS core.patients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_patient_id TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    date_of_birth DATE NOT NULL,
    gender TEXT,
    phone TEXT,
    language TEXT,
    pcp_provider_id BIGINT REFERENCES core.providers (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-------------------------------------------------------------------------------
-- 2.a ICD Dim Table - Optimized for ICD codes filtering
CREATE TABLE IF NOT EXISTS core.dim_icd (
    icd_code TEXT PRIMARY KEY,
    icd_family TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-------------------------------------------------------------------------------
-- 2.b DIAGNOSES - Optimized for chronic condition filtering
CREATE TABLE IF NOT EXISTS core.diagnoses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES core.patients (id) ON DELETE CASCADE,
    icd_code_ref TEXT REFERENCES core.dim_icd (icd_code),
    diagnosed_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uniq_normalized_diagnosis UNIQUE (patient_id, icd_code_ref, diagnosed_date)
);

CREATE INDEX IF NOT EXISTS idx_diagnoses_patient_id ON core.diagnoses (patient_id);

-------------------------------------------------------------------------------
-- 3.a Dim LAB TESTS
CREATE TABLE IF NOT EXISTS core.dim_lab_tests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-------------------------------------------------------------------------------
-- 3.b LAB RESULTS - Optimized for chronological trends
CREATE TABLE IF NOT EXISTS core.lab_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES core.patients (id) ON DELETE CASCADE,
    lab_test_id BIGINT NOT NULL REFERENCES core.dim_lab_tests (id),
    result_value NUMERIC(10, 2),
    result_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uniq_normalized_lab UNIQUE (
        patient_id,
        lab_test_id,
        result_value,
        result_date
    )
);

CREATE INDEX IF NOT EXISTS idx_labs_patient_date ON core.lab_results (patient_id, result_date DESC);

-------------------------------------------------------------------------------
-- 4.b ENCOUNTERS - Optimized with status constraints
CREATE TABLE IF NOT EXISTS core.encounters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES core.patients (id) ON DELETE CASCADE,
    provider_id BIGINT REFERENCES core.providers (id),
    encounter_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uniq_normalized_encounter UNIQUE (patient_id, provider_id, encounter_date)
);

CREATE INDEX IF NOT EXISTS idx_encounters_patient_id ON core.encounters (patient_id);
